### ISSUE TITLE
いいところ診断の結果に優しさを追加したい

### ISSUE THREAD

**Issue by Z1LF** [Z1LF/assessment#1]
以下の結果を追加したい

'{userName}のいいところは優しさです。あなたの優しい雰囲気や立ち振る舞いに多くの人が癒やされています。'

**Comment by Z1LF** [comment]
やります

**Comment by Z-I-L-F** [comment]
bec0285 で対応しました。

**Comment by Z1LF** [comment]
bec0285 で対応しました。
